spring:
  datasource:
    username: clinic_directory
    password: clinic_directory
    url: jdbc:mysql://localhost:3306/clinic_directory
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true